RentABook/Models/Address.cs
namespace RentABook.Models
{
    public class Address
    {
        public int AddressId { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string district { get; set; }
        public string Street { get; set; }
        public string Apartment { get; set; }
        public string Door { get; set; }
        public User User { get; set; }
    }
}

RentABook/Models/Book.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace RentABook.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; } = null!;

        public string Author { get; set; } = null!;

        public string? Country { get; set; }

        public string ImageLink { get; set; } = null!;

        public string? Language { get; set; }

        public int Page { get; set; } 

        public int Year { get; set; } 

        public string? Link { get; set; }

        public int PriceId { get; set; }
        public Price? Price { get; set; }

    }
}

RentABook/Models/ENUMS/GenderEnum.cs
namespace RentABook.Models.ENUMS
{
    public enum GenderEnum
    {
        Male,
        Female,
        DoesntMatter
    }
}

RentABook/Models/ErrorViewModel.cs
namespace RentABook.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RentABook/Models/Price.cs
using EntityFrameworkCore.Triggers;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace RentABook.Models
{
    public class Price
    {
        public int Id { get; set; }

        public double OriginalPrice { get; set; }

        public double DiscountRatio { get; set; }

        public double DiscountedPrice { get; set; }

        public Book Book { get; set; }

        public string? BookName { get; set; }

        public Price()
        {
            Triggers<Price>.Inserted += equals =>
            {
                if (DiscountRatio>0) {
                    DiscountedPrice = OriginalPrice * DiscountRatio;
                }
                else
                {
                    DiscountedPrice = OriginalPrice * 1;
                }
                
            };
        }

    }
}

RentABook/Models/User.cs
using RentABook.Models.ENUMS;

namespace RentABook.Models
{
    public class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public DateTime? BirthDate { get; set; }
        public GenderEnum?  Gender { get; set; }
        public List<Address> Addresses {  get; set; }

    }
}

RentABook/Models/bookViewModel.cs
namespace RentABook.Models
{
    public class bookViewModel
    {
        public string Title { get; set; }

        public string? Author { get; set; }

        public string? Country { get; set; }

        public string? Language { get; set; }

        public int? Page {  get; set; }

        public int? Year { get; set; }

        public IFormFile Resim { get; set; }

        public Price Price { get; set; }


    }
}

RentABook/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RentABook.Interfaces;
using RentABook.Models;
using RentABook.Repository;
using System.Diagnostics;

namespace RentABook.Controllers
{
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
  
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RentABook/Controllers/KitaplarController.cs
using Microsoft.AspNetCore.Mvc;
using RentABook.Interfaces;
using RentABook.Models;

namespace RentABook.Controllers
{
    public class KitaplarController : Controller
    {
        private readonly IBookRepository _bookRepository;
        public KitaplarController(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public async Task<IActionResult> Index()
        {
           IEnumerable<Book> books =await _bookRepository.GetAll();
            return View(books);
        }

        public  IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(bookViewModel bvm)
        {

            return View();
        }
    }
}

RentABook/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;

namespace RentABook.Controllers
{
    public class RegisterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RentABook/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="text-center h-100">
    <h1 class="display-4">berkayaşkım</h1>
    <p> BERKAY</p>
    <i class="bi bi-arrow-through-heart-fill"></i>
    <p>CEREN</p>
</div>

RentABook/Views/Kitaplar/Create.cshtml
@model bookViewModel
@* 
<div class="row">
    <div class="col">
        <!-- Name input -->
        <div data-mdb-input-init class="form-outline">
            <label asp-for="Title" class="form-label">Kitabın İsmi:</label>
            <input asp-for="Title" type="text" class="form-control" />  
        </div>
    </div>
    <div class="col">
        <!-- Author input -->
        <div data-mdb-input-init class="form-outline">
            <label asp-for="Author" class="form-label">Yazar:</label>
            <input asp-for="Author" type="text" class="form-control" />
        </div>
    </div>
</div>

<hr />

<div class="row">
    <div class="col">
        <!-- Name input -->
        <div data-mdb-input-init class="form-outline">
            <input type="text" id="form8Example3" class="form-control" />
            <label class="form-label" for="form8Example3">First name</label>
        </div>
    </div>
    <div class="col">
        <!-- Name input -->
        <div data-mdb-input-init class="form-outline">
            <input type="text" id="form8Example4" class="form-control" />
            <label class="form-label" for="form8Example4">Last name</label>
        </div>
    </div>
    <div class="col">
        <!-- Email input -->
        <div data-mdb-input-init class="form-outline">
            <input type="email" id="form8Example5" class="form-control" />
            <label class="form-label" for="form8Example5">Email address</label>
        </div>
    </div>
</div> *@
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" />

<div class="container-fluid px-1 py-4 mx-auto">
    <div class="row d-flex justify-content-center">
        <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">
            <link href="css/create.css" rel="stylesheet" />
            <h3>Kitap Ekle</h3>
            <p class="blue-text">Kitaplarını istediğin süre kadar kiralayabilirsin.</p>
            <div class="card">
               
                <form class="form-card m-3" >
                    <div class="row justify-content-between text-left ">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Kitabın Adı:<span class="text-danger"> *</span></label> <input asp-for="Title" type="text" id="fname" name="fname" placeholder="Enter your first name" onblur="validate(1)"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Yazar:<span class="text-danger"> *</span></label> <input asp-for="Author" type="text" id="lname" name="lname" placeholder="Enter your last name" onblur="validate(2)"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Kiralık Süresi<span class="text-danger"> *</span></label> <input type="text" id="email" name="email" placeholder="" onblur="validate(3)"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Ücret<span class="text-danger"> *</span></label> <input type="text" id="mob" name="mob" placeholder="" onblur="validate(4)"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Kitap Resmi:<span class="text-danger"> *</span></label> <input type="file" placeholder="resim"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-12 flex-column d-flex"> <label class="form-control-label px-3">Eklemek istediğin bir not ?<span class="text-danger"> *</span></label> <input type="text" id="ans" name="ans" placeholder="" onblur="validate(6)"> </div>
                    </div>
                    <div class="row justify-content-end">
                        <div class="form-group col-sm-6"> <button type="submit" class="btn btn-success w-100">Ekle</button> </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

RentABook/Views/Kitaplar/Index.cshtml
@model List<Book>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="~/css/@item.ImageLink"  height="500hv" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text"> @item.Title </p>
                            <p class="card-text"> @item.Language </p>
                            <p class="card-text"> @item.ImageLink </p>

                            <p class="card-text text-danger"> @item.Price.OriginalPrice </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Club" asp-action="Detail" asp-route-id="@item.Id"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </div>
                                <small class="text-muted">@item.Author</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

RentABook/Views/Register/Index.cshtml
<!-- Pills navs -->
<ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active"
           id="tab-login"
           data-mdb-pill-init
           href="#pills-login"
           role="tab"
           aria-controls="pills-login"
           aria-selected="true">Login</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link"
           id="tab-register"
           data-mdb-pill-init
           href="#pills-register"
           role="tab"
           aria-controls="pills-register"
           aria-selected="false">Register</a>
    </li>
</ul>
<!-- Pills navs -->
<!-- Pills content -->
<div class="tab-content">
    <div class="tab-pane fade show active"
         id="pills-login"
         role="tabpanel"
         aria-labelledby="tab-login">
        <form method="post">
            <div class="text-center mb-3">
                <p>Sign in with:</p>
                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1">
                    <i class="fab fa-facebook-f"></i>
                </button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1">
                    <i class="fab fa-google"></i>
                </button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1">
                    <i class="fab fa-twitter"></i>
                </button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1">
                    <i class="fab fa-github"></i>
                </button>
            </div>

            <p class="text-center">or:</p>

            <!-- Email input -->
            <div data-mdb-input-init class="form-outline mb-4">
                <input type="email" id="loginName" class="form-control" />
                <label class="form-label" for="loginName">Email or username</label>
            </div>

            <!-- Password input -->
            <div data-mdb-input-init class="form-outline mb-4">
                <input type="password" id="loginPassword" class="form-control" />
                <label class="form-label" for="loginPassword">Password</label>
            </div>

            <!-- 2 column grid layout -->
            <div class="row mb-4">
                <div class="col-md-6 d-flex justify-content-center">
                    <!-- Checkbox -->
                    <div class="form-check mb-3 mb-md-0">
                        <input class="form-check-input"
                               type="checkbox"
                               value=""
                               id="loginCheck"
                               checked />
                        <label class="form-check-label" for="loginCheck"> Remember me </label>
                    </div>
                </div>

                <div class="col-md-6 d-flex justify-content-center">
                    <!-- Simple link -->
                    <a href="#!">Forgot password?</a>
                </div>
            </div>

            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

            <!-- Register buttons -->
            <div class="text-center">
                <p>Not a member? <a href="#!">Register</a></p>
            </div>
        </form>
    </div>

    <div class="tab-pane fade"
         id="pills-register"
         role="tabpanel"
         aria-labelledby="tab-register">
        <form>
            <div class="text-center mb-3">
                <p>Sign up with:</p>
                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1">
                    <i class="fab fa-facebook-f"></i>
                </button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1">
                    <i class="fab fa-google"></i>
                </button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1">
                    <i class="fab fa-twitter"></i>
                </button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1">
                    <i class="fab fa-github"></i>
                </button>
            </div>

            <p class="text-center">or:</p>

            <!-- Name input -->
            <div data-mdb-input-init class="form-outline mb-4">
                <input type="text" id="registerName" class="form-control" />
                <label class="form-label" for="registerName">Name</label>
            </div>

            <!-- Username input -->
            <div data-mdb-input-init class="form-outline mb-4">
                <input type="text" id="registerUsername" class="form-control" />
                <label class="form-label" for="registerUsername">Username</label>
            </div>

            <!-- Email input -->
            <div data-mdb-input-init class="form-outline mb-4">
                <input type="email" id="registerEmail" class="form-control" />
                <label class="form-label" for="registerEmail">Email</label>
            </div>

            <!-- Password input -->
            <div data-mdb-input-init class="form-outline mb-4">
                <input type="password" id="registerPassword" class="form-control" />
                <label class="form-label" for="registerPassword">Password</label>
            </div>

            <!-- Repeat Password input -->
            <div data-mdb-input-init class="form-outline mb-4">
                <input type="password" id="registerRepeatPassword" class="form-control" />
                <label class="form-label" for="registerRepeatPassword">Repeat password</label>
            </div>

            <!-- Checkbox -->
            <div class="form-check d-flex justify-content-center mb-4">
                <input class="form-check-input me-2"
                       type="checkbox"
                       value=""
                       id="registerCheck"
                       checked
                       aria-describedby="registerCheckHelpText" />
                <label class="form-check-label" for="registerCheck">
                    I have read and agree to the terms
                </label>
            </div>

            <!-- Submit button -->
            <button data-mdb-ripple-init type="submit" class="btn btn-primary btn-block mb-3">Sign in</button>
        </form>
    </div>
</div>
<!-- Pills content -->

RentABook/Views/Shared/_Layout.cshtml
@* <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentABook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RentABook.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RentABook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item ms-auto p">
                            <a type="btn btn-success" asp-controller="Register" asp-action="Index" 
                               class="btn btn-success ">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RentABook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- Option 1: Include in HTML -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
 *@
      
<!DOCTYPE html>
<html lang="en" class="height: 100hv">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>

    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">RentABook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a asp-controller="Kitaplar" asp-action="Index" class="dropdown-item" >All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-4">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Kütüphanem</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Kitap Kiralama Sitesi</p>
                </div>
            </div>
        </header>
    <div class="container masthead ">
        @RenderBody()
    </div>
    <div class=" bottom-0 position-fixed w-100">     
        <footer class="py-3 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Kütüphanem 2024</p></div>
        </footer> 
    </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>